Add new properties to api
etalab/annuaire-entreprises-search-api pull request #78
Opened 2022-10-17 18:49 UTC by geoffreyaldebert

2022-10-24 10:16 UTC, geoffreyaldebert commented
Problems with e2e test is because e2e is confugured with your index @HAEKADI (because [changes here](https://github.com/etalab/annuaire-entreprises-search-infra/pull/61) are not taken into account. But it's working in my config. Can we bypass this test to merge ?

2022-10-24 12:28 UTC, geoffreyaldebert commented
This PR add new filters in API and reformat API's response. Here is the exhaustive list of what is added : 

New filters : 
- `est_rge` (true/false): Entreprises reconnues garantes de l'Environnement (RGE)
- `est_finess` (true/false): Entreprises ayant un établissement du domaine du sanitaire et social (FINESS)
- `est_uai` (true/false): Entreprises ayant un établissement UAI (Unité Administrative Immatriculée)
- `est_collectivite_territoriale` (true/false): Entreprises étant également une Collectivité territoriale
- `est_entrepreneur_spectacle`: Entreprises ayant une licence d'entrepreneur du spectacle
- `id_rge` (string): Identifiant RGE (reconnues garantes de l'Environnement) d'un établissement d'une entreprise
-  `id_convention_collective` (string): Identifiant de Convention Collective d'un établissement d'une entreprise
- `id_finess` (string): Identifiant FINESS d'un établissement d'une entreprise
- `id_uai` (string): Identifiant UAI d'un établissement d'une entreprise
- `code_collectivite_territoriale` (string): Code affiliée à une collectivité territoriale (Commune - code INSEE, EPCI - n° SIREN, Département - Code INSEE + "D", Région - Code INSEE)
- `nom_elu` (string): Nom d'un élu d'une collectivité territoriale
- `prenoms_elu` (string): Prenom(s) d'un élu d'une collectivité territoriale
- `date_naissance_elu_min` (date iso8601): Valeur minimale de la date de naissance de l'élu
- `date_naissance_elu_max` (date iso8601): Valeur maximale de la date de naissance de l'élu
- `nom_personne` (string): Nom d'une personne (dirigeant ou élu) d'une entreprise
- `prenoms_elu` (string): Prénoms d'une personne (dirigeant ou élu) d'une entreprise
- `date_naissance_elu_min` (date iso8601): Valeur minimale de la date de naissance de la personne
- `date_naissance_elu_max` (date iso8601): Valeur maximale de la date de naissance de la personne

Changes in API response:
- `complements` property which contains : 
  - `collectivite_territoriale` : null or object : 
    - `code` : code collectivité territoriale
    - `code_insee` : code insee de la collectivite territoriale
    - `elus` : élus de la collectivité territoriale
    - `niveau`: niveau de la collectivité territoriale
  - `convention_collective_renseignee`: true/false
  - `est_rge`: true/false
  - `est_finess`: true/false
  - `est_uai`: true/false

2022-10-24 13:42 UTC, XavierJp approved these changes

2022-10-24 13:45 UTC, geoffreyaldebert commented on aio/aio-proxy/aio_proxy/doc/open-api.yml
> +        - name: is_rge
oupsie

2022-10-24 13:47 UTC, geoffreyaldebert commented on aio/aio-proxy/aio_proxy/doc/open-api.yml
> +        - name: is_rge
ah mais c'est outdated tes remarques non ?

2022-10-24 13:47 UTC, geoffreyaldebert commented on aio/aio-proxy/aio_proxy/doc/open-api.yml
> +        - name: is_rge
il n'y a plus de is_rge mais un est_rge désormais

2022-11-04 10:29 UTC, HAEKADI commented
depends on #https://github.com/etalab/annuaire-entreprises-search-infra/pull/61

2022-11-07 16:54 UTC, HAEKADI requested changes

2022-11-07 16:54 UTC, HAEKADI commented on aio/aio-proxy/aio_proxy/parsers/bool_fields.py
> +        raise ValueError("{} doit prendre la valeur 'true' or 'false' !".format(param))
```suggestion
        raise ValueError(f"{param} doit prendre la valeur 'true' or 'false' !")
```

2022-11-07 16:54 UTC, HAEKADI commented on aio/aio-proxy/aio_proxy/parsers/string_parser.py
> +    param = param.replace("-", " ")
Why ?

2022-11-07 16:54 UTC, HAEKADI commented on aio/aio-proxy/aio_proxy/search/filters.py
> +def filter_search_is_exist(search, filters_to_process: list, **params):
The purpose of this function is not clear to me at all. I think a docstring should be added to explain what it does.

2022-11-07 16:54 UTC, HAEKADI commented on aio/aio-proxy/aio_proxy/search/filters.py
> +def filter_search_match_array(search, filters_to_process: list, **params):
Same here.

2022-11-07 16:54 UTC, HAEKADI commented on aio/aio-proxy/aio_proxy/search/person.py
> +    for p in properties:
`properties` is very vague

2022-11-07 16:54 UTC, HAEKADI commented on aio/aio-proxy/aio_proxy/search/person.py
> +    for p in properties:
Since this function is a little different than the "dirigeants search" one, I think a more elaborate explanation is in order.

2022-11-07 16:54 UTC, HAEKADI commented on aio/aio-proxy/aio_proxy/search/search_functions.py
> +    s = search_person(
I think this logic is a little too complicated, I had a hard time understanding it all.
I think we could possibly find a way to make it more simple 🤔

2022-11-07 16:57 UTC, HAEKADI commented
I solved all the bugs on the infra PR and indexed on the dev server, so the E2E tests no longer pose a problem.
I will test the tweaked search algorithm once we finish modifying the PR.

2022-11-10 12:27 UTC, HAEKADI approved these changes
The rest of API payload formatting will be handled in other Prs 🚀

2022-11-10 12:27 UTC, merged